version: "3.8"

networks:
  app-location_net:
    name: app-location_net
    driver: bridge
  app-wiremock_net:
    name: app-wiremock_net
    driver: bridge
    
services:
  app-location:
    container_name: app-location
    build:
      context: "./app"
    ports:
      - 8080:8080
    environment:
      BASE_URL_LOCATION: "http://app-wiremock:8081"
    networks:
      - app-location_net
      - app-wiremock_net

  app-wiremock:
    container_name: app-wiremock
    build:
      context: "./wiremock"
    ports:
      - 8081:8081
    networks:
      - app-wiremock_net